# Generated by Django 6.0.6 on 2026-06-30 11:26

import django.core.validators
import django.db.models.deletion
import recognition.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Accepted formats: JPG, JPEG, PNG. Max size: 5MB.', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), recognition.models.validate_image_size])),
                ('predicted_sign', models.CharField(blank=True, max_length=50)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Prediction confidence as a percentage (0-100).')),
                ('sign_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
