# Generated by Codex for the Django migration.

import django.conf
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(django.conf.settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationJob",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("docx", "DOCX"), ("jpg", "JPG"), ("png", "PNG")],
                        max_length=16,
                    ),
                ),
                ("detection_type", models.CharField(blank=True, max_length=32)),
                ("source_language", models.CharField(default="auto", max_length=32)),
                ("target_language", models.CharField(default="tagabawa", max_length=32)),
                ("ocr_languages", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=24,
                    ),
                ),
                ("progress", models.PositiveSmallIntegerField(default=0)),
                ("current_phase", models.CharField(default="queued", max_length=64)),
                ("current_step", models.CharField(default="Queued for processing", max_length=160)),
                ("phase_message", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("input_file_path", models.TextField(blank=True)),
                ("output_file_path", models.TextField(blank=True)),
                ("bilingual_file_path", models.TextField(blank=True)),
                ("structure_file_path", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translation_jobs",
                        to=django.conf.settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "-created_at"], name="translator__owner_i_940c04_idx"),
                    models.Index(fields=["status", "-created_at"], name="translator__status_0ee30e_idx"),
                ],
            },
        ),
    ]
