# Generated by Codex for media-backed upload tracking.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationjob",
            name="upload_file_path",
            field=models.TextField(blank=True),
        ),
    ]
