# Generated by Django 5.2.15 on 2026-06-12 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_rename_translationjob_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('autonym', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DatasetImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=24)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_failed', models.PositiveIntegerField(default=0)),
                ('error_report', models.JSONField(blank=True, default=list)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_number', models.PositiveIntegerField()),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('rotation', models.IntegerField(default=0)),
                ('source_image_path', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='translator.translationjob')),
            ],
            options={
                'ordering': ['job', 'page_number'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_type', models.CharField(choices=[('translated_pdf', 'Translated PDF'), ('bilingual_aligned', 'Aligned bilingual document'), ('bilingual_alternating', 'Alternating bilingual PDF'), ('structure_json', 'Structure JSON'), ('preview_image', 'Preview image')], max_length=32)),
                ('file_format', models.CharField(default='pdf', max_length=16)),
                ('file_path', models.TextField()),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_outputs', to='translator.translationjob')),
            ],
            options={
                'ordering': ['job', 'output_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LanguagePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_pairs', to='translator.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='target_pairs', to='translator.language')),
            ],
            options={
                'ordering': ['source_language__name', 'target_language__name'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_term', models.CharField(max_length=255)),
                ('target_term', models.CharField(max_length=255)),
                ('domain', models.CharField(blank=True, db_index=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_glossary_terms', to=settings.AUTH_USER_MODEL)),
                ('language_pair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='glossary_terms', to='translator.languagepair')),
            ],
            options={
                'ordering': ['domain', 'source_term'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engine', models.CharField(default='tesseract', max_length=80)),
                ('language_codes', models.CharField(blank=True, max_length=128)),
                ('text', models.TextField(blank=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending review'), ('accepted', 'Accepted'), ('corrected', 'Corrected'), ('rejected', 'Rejected')], db_index=True, default='pending_review', max_length=24)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='translator.translationjob')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='translator.documentpage')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ocr_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['job', 'page__page_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PhrasebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(blank=True, db_index=True, max_length=120)),
                ('english', models.TextField(blank=True)),
                ('tagabawa', models.TextField(blank=True)),
                ('filipino', models.TextField(blank=True)),
                ('cebuano', models.TextField(blank=True)),
                ('source', models.CharField(default='phrasebook', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sme_verified', models.BooleanField(db_index=True, default=False)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['topic', 'english', 'id'],
                'indexes': [models.Index(fields=['is_active', 'needs_review'], name='translator__is_acti_619ae3_idx'), models.Index(fields=['is_sme_verified', 'needs_review'], name='translator__is_sme__ffb3f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=16)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_events', to='translator.translationjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_index', models.PositiveIntegerField()),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField(blank=True)),
                ('source_language', models.CharField(max_length=32)),
                ('target_language', models.CharField(max_length=32)),
                ('method', models.CharField(blank=True, max_length=64)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('bbox', models.JSONField(blank=True, default=list)),
                ('glossary_matches', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='translator.translationjob')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_segments', to='translator.documentpage')),
            ],
            options={
                'ordering': ['job', 'segment_index'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('jpg', 'JPG'), ('png', 'PNG')], max_length=16)),
                ('file_path', models.TextField()),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document', to='translator.translationjob')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('object_type', models.CharField(blank=True, max_length=120)),
                ('object_id', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentpage',
            constraint=models.UniqueConstraint(fields=('job', 'page_number'), name='translator_unique_page_per_job'),
        ),
        migrations.AddIndex(
            model_name='generatedoutput',
            index=models.Index(fields=['job', 'output_type'], name='translator__job_id_e95fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedoutput',
            index=models.Index(fields=['file_format', '-created_at'], name='translator__file_fo_11163f_idx'),
        ),
        migrations.AddConstraint(
            model_name='generatedoutput',
            constraint=models.UniqueConstraint(fields=('job', 'output_type', 'file_path'), name='translator_unique_generated_output_path'),
        ),
        migrations.AddConstraint(
            model_name='languagepair',
            constraint=models.UniqueConstraint(fields=('source_language', 'target_language'), name='translator_unique_language_pair'),
        ),
        migrations.AddConstraint(
            model_name='languagepair',
            constraint=models.CheckConstraint(condition=models.Q(('source_language', models.F('target_language')), _negated=True), name='translator_language_pair_not_identity'),
        ),
        migrations.AddConstraint(
            model_name='glossaryterm',
            constraint=models.UniqueConstraint(fields=('language_pair', 'source_term', 'target_term'), name='translator_unique_glossary_term'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['job', 'status'], name='translator__job_id_f1a5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='ocrresult',
            index=models.Index(fields=['engine', 'status'], name='translator__engine_2bc0f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='ocrresult',
            constraint=models.UniqueConstraint(fields=('job', 'page', 'engine'), name='translator_unique_ocr_result_per_page_engine'),
        ),
        migrations.AddIndex(
            model_name='systemeventlog',
            index=models.Index(fields=['level', '-created_at'], name='translator__level_a18f21_idx'),
        ),
        migrations.AddIndex(
            model_name='systemeventlog',
            index=models.Index(fields=['event_type', '-created_at'], name='translator__event_t_19825f_idx'),
        ),
        migrations.AddIndex(
            model_name='translationsegment',
            index=models.Index(fields=['job', 'needs_review'], name='translator__job_id_bf7059_idx'),
        ),
        migrations.AddIndex(
            model_name='translationsegment',
            index=models.Index(fields=['source_language', 'target_language'], name='translator__source__4001a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='translationsegment',
            constraint=models.UniqueConstraint(fields=('job', 'segment_index'), name='translator_unique_segment_per_job'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['owner', '-created_at'], name='translator__owner_i_13c040_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocument',
            index=models.Index(fields=['file_type', '-created_at'], name='translator__file_ty_46f3c7_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', '-created_at'], name='translator__user_id_9351b7_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['action', '-created_at'], name='translator__action_0a0ef9_idx'),
        ),
    ]
