# Generated by Django 5.2.15 on 2026-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0004_language_datasetimportbatch_documentpage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationjob',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('jpg', 'JPG'), ('png', 'PNG'), ('txt', 'Text')], max_length=16),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('jpg', 'JPG'), ('png', 'PNG'), ('txt', 'Text')], max_length=16),
        ),
    ]
